#!/bin/bash
# Generated by codegen_tool

RUNNER_SCRIPT_DIR=$(cd ${0%/*} && pwd)

LOCK_FILE=/var/lock/mira_bdb_port_driver.vm.pipe.lock

I_AM=`whoami`

if [ "$I_AM" == "developer" ]; then

    dotlockfile -p -l -r 2 $LOCK_FILE
    GOT_LOCK=$?

    if [ $GOT_LOCK -ne 0 ]; then
        echo "Could not lock: $LOCK_FILE"
        exit 1
    else
	${RUNNER_SCRIPT_DIR}/../bin/mira_bdb_port_driver  attach 
    fi

    dotlockfile -u $LOCK_FILE

else
    echo "You must be user 'developer' to run this script!"
fi


#EOF
