FROM registry.miranetworks.net/miranetworks/dev_ubuntu_trusty_erlang_17.4

RUN apt-get clean && apt-get update && apt-get install -y libdb5.3-dev
#                                        s3cmd \
#                                        gawk

