#!/bin/bash

PATH=/bin:/usr/bin:/sbin:/usr/sbin
START=/usr/sbin/start_kvs_bdb.sh
STOP=/usr/sbin/stop_kvs_bdb.sh

DATA_DIR=/var/lib/kvs_bdb
PID_DIR=/var/run/kvs_bdb

DBNAME=example
DBHOME=${DATA_DIR}/${DBNAME}
DBPIDFILE=${PID_DIR}/${DBNAME}.pid
DBUSER=kvsbdb
IP=0.0.0.0
PORT=22122
LOGGING="-l"

if [ -d ${DATA_DIR} ]; then

    echo "${DATA_DIR} exists."

else

    mkdir -p ${DATA_DIR}
    chown -R ${DBUSER}:${DBUSER} ${DATA_DIR}
 
fi

if [ -d ${PID_DIR} ]; then

    echo "${PID_DIR} exists."

else

    mkdir -p ${PID_DIR}
    chown -R ${DBUSER}:${DBUSER} ${PID_DIR}
 
fi

case "$1" in
  start)

        if [ -d ${DBHOME} ]; then
            echo "${DBHOME} exists."
        else

            mkdir -p ${DBHOME}
            chown -R ${DBUSER}:${DBUSER} ${DBHOME}
 
        fi

        if [ -f ${DBPIDFILE} ]; then

            echo "${DBPIDFILE} exists."

        else

            touch ${DBPIDFILE}
            chown -R ${DBUSER}:${DBUSER} ${DBPIDFILE}

        fi

        cd ${DBHOME}
        echo -n "Starting kvs_db in ${DBHOME} on ${IP}:${PORT}"
        su ${DBUSER} -c "${START} ${DBNAME} ${DBHOME} ${DBPIDFILE} ${IP} ${PORT} ${LOGGING}"
        echo "."
        ;;
  stop)
        echo -n "Stopping kvs_db in ${DBHOME} on ${IP}:${PORT}"
        echo "."
        ;;
  *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit 0



EOF
