#!/usr/bin/env escript
%% -*- erlang -*-
%%! -pa deps/cuttlefish/ebin

main(Args) ->

    [ConfigFile, SchemaDir] = Args,

    {_, Mappings, _} = cuttlefish_schema:files(filelib:wildcard(SchemaDir ++ "/*.schema")),

    ok = cuttlefish_conf:generate_file(Mappings, ConfigFile).

%%EOF
